- hosts: localhost
   gather_facts: False
   become: false
   tasks:
   - name: List all function
     lambda_facts:
       region: ap-south-1
       aws_access_key: 
       aws_secret_key: 
       query: all
       #function_name: insufficientalarm
     register: _lambda_facts
   - set_fact:
       lnbda: "{{ _lambda_facts.ansible_facts.lambda_facts.function|list }}"

   - ec2_metric_alarm:
      name: "Lambda Alarm- {{ item }}"
      state: present
      aws_access_key: 
      aws_secret_key:
      region: us-west-2
      metric: "Errors"
      namespace: "AWS/Lambda"
      statistic: Average
      comparison: ">="
      threshold: 1
      period: 60
      evaluation_periods: 1
      #unit: "Percent
      dimensions: "{'FunctionName':'{{ item }}'}"
     when: "'RunProg' ==  '{{ item }}'"
     with_items: "{{ lnbda }}"
     #when: '"RunProg" is undefind'
...
